version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
    links:
      - redis
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
      - /user/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 3000
  redis:
    image: redis:latest
    expose:
      - 6379 
    command: redis-server --requirepass victorcastr
    environment:
      REDIS_PASSWORD: victorcastr